export default goals = {
  FirstSteps: {
    title: 'First steps',
    text: '1 hour smoke-free',
    type: 'time',
    goalValue: 1,
  },
  VictoryHour: {
    title: 'Victory hour',
    text: '5 hours smoke-free',
    type: 'time',
    goalValue: 5,
  },
  HalfDayVictory: {
    title: 'Half-day victory',
    text: '12 hours smoke-free',
    type: 'time',
    goalValue: 12,
  },
  SmokeFreeDay: {
    title: 'Smoke-free day',
    text: '24 hours smoke-free',
    type: 'time',
    goalValue: 24,
  },
  FullWeekSuccess: {
    title: 'Full week success',
    text: '7 days smoke-free',
    type: 'time',
    goalValue: 168,
  },
  TwoWeekMilestone: {
    title: 'Two-week milestone',
    text: '14 days smoke-free',
    type: 'time',
    goalValue: 336,
  },
  SmallVictory: {
    title: 'Small victory',
    text: '21 days smoke-free',
    type: 'time',
    goalValue: 504,
  },
  VictoryMonth: {
    title: 'Victory month',
    text: '1 month smoke-free',
    type: 'time',
    goalValue: 720,
  },
  OneAndHalfMonths: {
    title: 'One and a half months',
    text: '45 days smoke-free',
    type: 'time',
    goalValue: 1080,
  },
  DoubleMonth: {
    title: 'Double month',
    text: '2 months smoke-free',
    type: 'time',
    goalValue: 1440,
  },
  GoldenAchievement: {
    title: 'Golden achievement',
    text: '3 months smoke-free',
    type: 'time',
    goalValue: 2160,
  },
  DaysFree: {
    title: '100 days free',
    text: '100 days smoke-free',
    type: 'time',
    goalValue: 2400,
  },
  HalfYearMilestone: {
    title: 'Half year milestone',
    text: '6 months smoke-free',
    type: 'time',
    goalValue: 4320,
  },
  NineMonthsAchievement: {
    title: 'Nine months achievement',
    text: '9 months smoke-free',
    type: 'time',
    goalValue: 6480,
  },
  YearlyTriumph: {
    title: 'Yearly Triumph',
    text: '1 year smoke-free',
    type: 'time',
    goalValue: 8760,
  },
  StayingStrong: {
    title: 'Staying strong',
    text: '1.5 years smoke-free',
    type: 'time',
    goalValue: 13140,
  },
  TwoYearLegend: {
    title: 'Two-year legend',
    text: '2 years smoke-free',
    type: 'time',
    goalValue: 17520,
  },
  FirstMilestone: {
    title: 'First milestone',
    text: 'Saved $50',
    type: 'money',
    goalValue: 50,
  },
  NextGoal: {
    title: 'Next goal',
    text: 'Saved $200',
    type: 'money',
    goalValue: 200,
  },
  Achiever: {
    title: 'Achiever',
    text: 'Saved $500',
    type: 'money',
    goalValue: 500,
  },
  CoffeeMoney: {
    title: 'Coffee money',
    text: 'Saved $750',
    type: 'money',
    goalValue: 750,
  },
  GreatSavings: {
    title: 'Great saving',
    text: 'Saved 1,000$',
    type: 'money',
    goalValue: 1000,
  },
  OnRoll: {
    title: 'On a roll',
    text: 'Saved $2,500',
    type: 'money',
    goalValue: 2500,
  },
  MajorProgress: {
    title: 'Major progress',
    text: 'Saved $5,000',
    type: 'money',
    goalValue: 5000,
  },
  SupportiveStart: {
    title: 'Supportive start',
    text: 'Subscribed for 1 month',
    type: 'subscription',
    goalValue: 1,
  },
  Dedicated: {
    title: 'Dedicated',
    text: 'Subscribed for 3 months',
    type: 'subscription',
    goalValue: 3,
  },
  ConsistentEffort: {
    title: 'Consistent effort',
    text: 'Subscribed for 6 months',
    type: 'subscription',
    goalValue: 6,
  },
  LongTermSupport: {
    title: 'Long-term support',
    text: 'Subscribed for 1 year',
    type: 'subscription',
    goalValue: 12,
  },
  FreshStart: {
    title: 'Fresh start',
    text: 'Improved breathing',
    type: 'weekly',
    goalValue: 1,
  },
  EnergyInDay: {
    title: 'Energy in the day',
    text: 'Increased energy',
    type: 'weekly',
    goalValue: 2,
  },
  ClearSkin: {
    title: 'Clear skin',
    text: 'Improved skin condition',
    type: 'weekly',
    goalValue: 3,
  },
  HealthyHeart: {
    title: 'Healthy heart',
    text: 'Lower blood pressure',
    type: 'weekly',
    goalValue: 4,
  },
  BetterTaste: {
    title: 'Better taste',
    text: 'Improved in teste sensation',
    type: 'weekly',
    goalValue: 5,
  },
  HealthySleep: {
    title: 'Healthy sleep',
    text: 'Improved quality of sleep',
    type: 'weekly',
    goalValue: 6,
  },
  ImprovedConcentration: {
    title: 'Improved concentration',
    type: 'weekly',
    text: 'Improved focus',
    goalValue: 7,
  },
  LessStress: {
    title: 'Less stress',
    text: 'Reduced stress',
    type: 'weekly',
    goalValue: 8,
  },
  ActiveLifestyle: {
    title: 'Active lifestyle',
    text: 'Increased activity',
    type: 'weekly',
    goalValue: 9,
  },
  FreshnessBreath: {
    title: 'Freshness of breath',
    text: 'Improved freshness of breath',
    type: 'weekly',
    goalValue: 10,
  },
  FewerHeadaches: {
    title: 'Fewer headaches',
    text: 'Reducing headaches',
    type: 'weekly',
    goalValue: 11,
  },
  StrongImmunity: {
    title: 'Strong immunity',
    text: 'Strengthening of the immune system',
    type: 'weekly',
    goalValue: 12,
  },
  Metabolism: {
    title: 'Metabolism',
    text: 'Normalization of metabolism',
    type: 'weekly',
    goalValue: 13,
  },
  NewBeginnings: {
    title: 'New beginnings',
    text: 'Energy for hobbies',
    type: 'weekly',
    goalValue: 14,
  },
  SelfCare: {
    title: 'Self-care',
    text: 'Improved hygiene',
    type: 'weekly',
    goalValue: 15,
  },
  Calmness: {
    title: 'Calmness',
    text: 'Ease of relaxation',
    type: 'weekly',
    goalValue: 16,
  },
  GeneralWellBeing: {
    title: 'General well-being',
    text: 'Increased comfort',
    type: 'weekly',
    goalValue: 17,
  },
  Vitality: {
    title: 'Vitality',
    text: 'More energy and motivation',
    type: 'weekly',
    goalValue: 18,
  },
  CaringForAppearance: {
    title: 'Caring for appearance',
    text: 'Improved hair nad nails',
    type: 'weekly',
    goalValue: 19,
  },
  PsychologicalWellBeing: {
    title: 'Psychological well-being',
    text: 'Improved emotional well-being',
    type: 'weekly',
    goalValue: 20,
  },
  FewerAllergies: {
    title: 'Fewer allergies',
    text: 'Reduced allergies',
    type: 'weekly',
    goalValue: 21,
  },
  BloodCirculation: {
    title: 'Blood circulation',
    text: 'Improved circulation',
    type: 'weekly',
    goalValue: 22,
  },
  MuscleTone: {
    title: 'Muscle tone',
    text: 'Improved muscle elasticity',
    type: 'weekly',
    goalValue: 23,
  },
  ColdResistance: {
    title: 'Cold resistance',
    text: 'Fewer illness',
    type: 'weekly',
    goalValue: 24,
  },
  EmotionalStability: {
    title: 'Emotional stability',
    text: 'Better emotional stability',
    type: 'weekly',
    goalValue: 25,
  },
  DentalHealth: {
    title: 'Dental healh',
    text: 'Better teeth and gums',
    type: 'weekly',
    goalValue: 26,
  },
  HealthDigestion: {
    title: 'Health digestion',
    text: 'Normalization of the GI tract',
    type: 'weekly',
    goalValue: 27,
  },
  JoyLife: {
    title: 'Joy of life',
    text: 'Increased happiness',
    type: 'weekly',
    goalValue: 28,
  },
  PhysicalFlexibility: {
    title: 'Physical flexibility',
    text: 'Improved joint mobility',
    type: 'weekly',
    goalValue: 29,
  },
  QuickRecovery: {
    title: 'Quick recovery',
    text: 'Quicker recovery from exertion',
    type: 'weekly',
    goalValue: 30,
  },
}

// export default goals = {
//   FirstSteps: {
//     title: 'First steps',
//     text: '1 hour smoke-free',
//     type: 'time',
//     goalValue: 1,
//   },
//   VictoryHour: {
//     title: 'Victory hour',
//     text: '5 hours smoke-free',
//     type: 'time',
//     goalValue: 5,
//   },
//   HalfDayVictory: {
//     title: 'Half-day victory',
//     text: '12 hours smoke-free',
//     type: 'time',
//     goalValue: 12,
//   },
//   SmokeFreeDay: {
//     title: 'Smoke-free day',
//     text: '24 hours smoke-free',
//     type: 'time',
//     goalValue: 24,
//   },
//   FullWeekSuccess: {
//     title: 'Full week success',
//     text: '7 days smoke-free',
//     type: 'time',
//     goalValue: 168,
//   },
//   TwoWeekMilestone: {
//     title: 'Two-week milestone',
//     text: '14 days smoke-free',
//     type: 'time',
//     goalValue: 336,
//   },
//   SmallVictory: {
//     title: 'Small victory',
//     text: '21 days smoke-free',
//     type: 'time',
//     goalValue: 504,
//   },
//   VictoryMonth: {
//     title: 'Victory month',
//     text: '1 month smoke-free',
//     type: 'time',
//     goalValue: 720,
//   },
//   OneAndHalfMonths: {
//     title: 'One and a half months',
//     text: '45 days smoke-free',
//     type: 'time',
//     goalValue: 1080,
//   },
//   DoubleMonth: {
//     title: 'Double month',
//     text: '2 months smoke-free',
//     type: 'time',
//     goalValue: 1440,
//   },
//   GoldenAchievement: {
//     title: 'Golden achievement',
//     text: '3 months smoke-free',
//     type: 'time',
//     goalValue: 2160,
//   },
//   DaysFree: {
//     title: '100 days free',
//     text: '100 days smoke-free',
//     type: 'time',
//     goalValue: 2400,
//   },
//   HalfYearMilestone: {
//     title: 'Half year milestone',
//     text: '6 months smoke-free',
//     type: 'time',
//     goalValue: 4320,
//   },
//   NineMonthsAchievement: {
//     title: 'Nine months achievement',
//     text: '9 months smoke-free',
//     type: 'time',
//     goalValue: 6480,
//   },
//   YearlyTriumph: {
//     title: 'Yearly Triumph',
//     text: '1 year smoke-free',
//     type: 'time',
//     goalValue: 8760,
//   },
//   StayingStrong: {
//     title: 'Staying strong',
//     text: '1.5 years smoke-free',
//     type: 'time',
//     goalValue: 13140,
//   },
//   TwoYearLegend: {
//     title: 'Two-year legend',
//     text: '2 years smoke-free',
//     type: 'time',
//     goalValue: 17520,
//   },
//   FirstMilestone: {
//     title: 'First milestone',
//     text: 'Saved $50',
//     type: 'money',
//     goalValue: 50,
//   },
//   NextGoal: {
//     title: 'Next goal',
//     text: 'Saved $200',
//     type: 'money',
//     goalValue: 200,
//   },
//   Achiever: {
//     title: 'Achiever',
//     text: 'Saved $500',
//     type: 'money',
//     goalValue: 500,
//   },
//   CoffeeMoney: {
//     title: 'Coffee money',
//     text: 'Saved $750',
//     type: 'money',
//     goalValue: 750,
//   },
//   GreatSavings: {
//     title: 'Great saving',
//     text: 'Saved 1,000$',
//     type: 'money',
//     goalValue: 1000,
//   },
//   OnRoll: {
//     title: 'On a roll',
//     text: 'Saved $2,500',
//     type: 'money',
//     goalValue: 2500,
//   },
//   MajorProgress: {
//     title: 'Major progress',
//     text: 'Saved $5,000',
//     type: 'money',
//     goalValue: 5000,
//   },
//   SupportiveStart: {
//     title: 'Supportive start',
//     text: 'Subscribed for 1 month',
//     type: 'subscription',
//     goalValue: 1,
//   },
//   Dedicated: {
//     title: 'Dedicated',
//     text: 'Subscribed for 3 months',
//     type: 'subscription',
//     goalValue: 3,
//   },
//   ConsistentEffort: {
//     title: 'Consistent effort',
//     text: 'Subscribed for 6 months',
//     type: 'subscription',
//     goalValue: 6,
//   },
//   LongTermSupport: {
//     title: 'Long-term support',
//     text: 'Subscribed for 1 year',
//     type: 'subscription',
//     goalValue: 12,
//   },
//   FreshStart: {
//     title: 'Fresh start',
//     text: 'Improved breathing',
//     type: 'weekly',
//     goalValue: 1,
//   },
//   EnergyInDay: {
//     title: 'Energy in the day',
//     text: 'Increased energy',
//     type: 'weekly',
//     goalValue: 2,
//   },
//   ClearSkin: {
//     title: 'Clear skin',
//     text: 'Improved skin condition',
//     type: 'weekly',
//     goalValue: 3,
//   },
//   HealthyHeart: {
//     title: 'Healthy heart',
//     text: 'Lower blood pressure',
//     type: 'weekly',
//     goalValue: 4,
//   },
//   BetterTaste: {
//     title: 'Better taste',
//     text: 'Improved in teste sensation',
//     type: 'weekly',
//     goalValue: 5,
//   },
//   HealthySleep: {
//     title: 'Healthy sleep',
//     text: 'Improved quality of sleep',
//     type: 'weekly',
//     goalValue: 6,
//   },
//   ImprovedConcentration: {
//     title: 'Improved concentration',
//     type: 'weekly',
//     text: 'Improved focus',
//     goalValue: 7,
//   },
//   LessStress: {
//     title: 'Less stress',
//     text: 'Reduced stress',
//     type: 'weekly',
//     goalValue: 8,
//   },
//   ActiveLifestyle: {
//     title: 'Active lifestyle',
//     text: 'Increased activity',
//     type: 'weekly',
//     goalValue: 9,
//   },
//   FreshnessBreath: {
//     title: 'Freshness of breath',
//     text: 'Improved freshness of breath',
//     type: 'weekly',
//     goalValue: 10,
//   },
//   FewerHeadaches: {
//     title: 'Fewer headaches',
//     text: 'Reducing headaches',
//     type: 'weekly',
//     goalValue: 11,
//   },
//   StrongImmunity: {
//     title: 'Strong immunity',
//     text: 'Strengthening of the immune system',
//     type: 'weekly',
//     goalValue: 12,
//   },
//   Metabolism: {
//     title: 'Metabolism',
//     text: 'Normalization of metabolism',
//     type: 'weekly',
//     goalValue: 13,
//   },
//   NewBeginnings: {
//     title: 'New beginnings',
//     text: 'Energy for hobbies',
//     type: 'weekly',
//     goalValue: 14,
//   },
//   SelfCare: {
//     title: 'Self-care',
//     text: 'Improved hygiene',
//     type: 'weekly',
//     goalValue: 15,
//   },
//   Calmness: {
//     title: 'Calmness',
//     text: 'Ease of relaxation',
//     type: 'weekly',
//     goalValue: 16,
//   },
//   GeneralWellBeing: {
//     title: 'General well-being',
//     text: 'Increased comfort',
//     type: 'weekly',
//     goalValue: 17,
//   },
//   Vitality: {
//     title: 'Vitality',
//     text: 'More energy and motivation',
//     type: 'weekly',
//     goalValue: 18,
//   },
//   CaringForAppearance: {
//     title: 'Caring for appearance',
//     text: 'Improved hair nad nails',
//     type: 'weekly',
//     goalValue: 19,
//   },
//   PsychologicalWellBeing: {
//     title: 'Psychological well-being',
//     text: 'Improved emotional well-being',
//     type: 'weekly',
//     goalValue: 20,
//   },
//   FewerAllergies: {
//     title: 'Fewer allergies',
//     text: 'Reduced allergies',
//     type: 'weekly',
//     goalValue: 21,
//   },
//   BloodCirculation: {
//     title: 'Blood circulation',
//     text: 'Improved circulation',
//     type: 'weekly',
//     goalValue: 22,
//   },
//   MuscleTone: {
//     title: 'Muscle tone',
//     text: 'Improved muscle elasticity',
//     type: 'weekly',
//     goalValue: 23,
//   },
//   ColdResistance: {
//     title: 'Cold resistance',
//     text: 'Fewer illness',
//     type: 'weekly',
//     goalValue: 24,
//   },
//   EmotionalStability: {
//     title: 'Emotional stability',
//     text: 'Better emotional stability',
//     type: 'weekly',
//     goalValue: 25,
//   },
//   DentalHealth: {
//     title: 'Dental healh',
//     text: 'Better teeth and gums',
//     type: 'weekly',
//     goalValue: 26,
//   },
//   HealthDigestion: {
//     title: 'Health digestion',
//     text: 'Normalization of the GI tract',
//     type: 'weekly',
//     goalValue: 27,
//   },
//   JoyLife: {
//     title: 'Joy of life',
//     text: 'Increased happiness',
//     type: 'weekly',
//     goalValue: 28,
//   },
//   PhysicalFlexibility: {
//     title: 'Physical flexibility',
//     text: 'Improved joint mobility',
//     type: 'weekly',
//     goalValue: 29,
//   },
//   QuickRecovery: {
//     title: 'Quick recovery',
//     text: 'Quicker recovery from exertion',
//     type: 'weekly',
//     goalValue: 30,
//   },
// }
