export default {
  goals: {
    'First steps': '1 hour smoke-free',
    'Victory Hour': '2 hours smoke-free',
    'Fresh start': '4 hours smoke-free',
    'Smokefree Day': '24 hours smoke free',
    'First weekend': '2 days without smoking',
    'Triple success': '3 days without smoking',
    'A stress-free weekend': '4 days without smoking',
    Workweek: '5 smoke-free days',
    'Small Week': '7 days without smoking',
    'Stage two': '10 days without smoking',
    'Victory Month': '1 month smoke-free',
    Stability: '45 days without smoking',
    'Two months smoke-free': '2 months smoke-free',
    'The golden milestone': '3 months smoke-free',
    '100 days clean': '100 days smoke-free',
    'Semi-annual triumph': '6 months smoke-free',
    'Nine months': '9 months smoke-free',
    'A year and a bit more': '13 months smoke-free',
    'A year and a half smoke-free': '18 months smoke-free',
    'Two-year knight': '2 years smoke-free',
    'Three years of experience': '3 years smoke-free',
    'Five-year heroism': '5 years smoke-free',
    'Small savings': '$50 saved',
    'Small reward': '$100 saved',
    'Financial Startup': 'Saved $200',
    'Average contribution': '$500 saved',
    'Coffee money': '$750 saved',
    'A solid sum': '$1,000 saved',
    'Significant savings': '$1,500 saved',
    'Big result': '$2,000 saved',
    'Fresh Start': 'Noticeable improvement in breathing',
    'Energy in the Day': 'Increase overall energy levels',
    'Clear skin': 'Improves skin condition',
    'Healthy heart': 'Lower blood pressure or improve heart function',
    'Better Taste': 'Improved taste sensation',
    'Healthy sleep': 'Improving the quality of sleep',
    'Improved concentration': 'Increased ability to focus and improved memory',
    'Less Stress': 'Noticeable reduction in stress and anxiety levels',
    'Active Lifestyle': 'Increased physical activity and ease of exercise',
    'Freshness of breath': 'Noticeable improvement in freshness of breath',
    'Fewer headaches': 'Reduced frequency of headaches or migraines',
    'Immune System Strength': 'Strengthen the immune system, less frequency of illness',
    'Improved metabolism': 'Normalize metabolism and improve overall health',
    'Energy for new endeavors': 'Increased desire and ability to pursue new hobbies and projects',
    'Self-care': 'More frequent attention to personal hygiene and self-care',
    'Calm and relaxed': 'It is easier to deal with tense situations and feel relaxed',
    'General well-being': 'Increased overall comfort and health throughout the day',
    'New vitality': 'Feeling more dynamism and motivation',
    'Caring for your appearance': 'Improving the condition of your hair and nails',
    'Psychological well-being': 'Noticeable improvement in psychological state and emotional background',
    'Fewer allergies': 'Reduced frequency or symptoms of allergic reactions',
    'Improved blood circulation': 'Noticeable improvement in circulation and temperature of hands and feet',
    'Improving muscle tone': 'Improves muscle tone and elasticity',
    'Resistance to colds': 'Fewer cases of colds and viruses',
    'Emotional resilience': 'Improved ability to cope with emotional upheaval',
    'Dental care': 'Noticeable improvement in the condition of teeth and gums',
    'Healthy digestion': 'Normalize the digestive system and reduce stomach problems',
    'Joy in Life': 'Increased overall sense of joy and fulfillment',
    'Physical flexibility': 'Increase body flexibility and improve joint mobility',
    'Recovery after exertion': 'Quick recovery from physical and emotional stress',
  },
}
